# Generated by Django 5.0.6 on 2024-07-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableTennis', '0003_rename_games_played_duostats_matches_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchduostats',
            name='games_played',
        ),
    ]
