# Generated by Django 5.0.6 on 2024-07-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableTennis', '0007_rename_tournament_tournamentinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchduostats',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='matchsinglestats',
            name='winner',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentinfo',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
    ]
