# Generated by Django 5.0.6 on 2024-07-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableTennis', '0002_rename_tabletennisduo_duo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duostats',
            old_name='games_played',
            new_name='matches_played',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
