# Generated by Django 5.0.6 on 2024-07-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableTennis', '0004_remove_matchduostats_games_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duostats',
            name='matches_played',
        ),
    ]
