# Generated by Django 5.0.6 on 2024-07-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_matchteamstats_team_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='parent_match_team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_matches_team1', to='football.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='parent_match_team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_matches_team2', to='football.match'),
        ),
    ]
