# Generated by Django 5.0.6 on 2024-07-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_match_parent_match_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='football.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='football.team'),
        ),
    ]
