# Generated by Django 5.0.6 on 2024-07-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_alter_match_team_1_alter_match_team_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.matchstats'),
        ),
    ]
