# Generated by Django 5.0.6 on 2024-07-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_match_match_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='parent_match_team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='parent_match_team2',
        ),
        migrations.CreateModel(
            name='MatchParenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.SmallIntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_parenting', to='football.match')),
                ('parent_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_match', to='football.match')),
            ],
        ),
    ]
