# Generated by Django 5.0.6 on 2024-07-29 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_remove_match_winner_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.team'),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
