# Generated by Django 5.0.6 on 2024-07-30 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_alter_matchteamstats_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstats',
            name='team_1_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_team1', to='football.matchteamstats'),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='team_2_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_team2', to='football.matchteamstats'),
        ),
    ]
