# Generated by Django 5.0.6 on 2024-07-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_rename_match_matchparenting_child_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
